### ISSUE TITLE
is it possible with a shell-based approach?

### ISSUE THREAD

**Issue by brandonzylstra** [k0nserv/kitty-icon#11]
> Drag the .icns file for your favourite variant from build/ onto the application icon in the kitty info pane.

Is it possible to do this without manually dragging and dropping an icon in the Finder?  This gets very old after every update to Kitty.

I have written a script but it is missing just that one step:
https://gist.github.com/brandondrew/dd5124cf3b4621b82f3522cb823ece77

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/faq/#i-do-not-like-the-kitty-icon tells you how to change the icon programatically.
