### ISSUE TITLE
You can edit Gentoo ebuild: add USE flag to use this ico

### ISSUE THREAD

**Issue by vitaly-zdanevich** [k0nserv/kitty-icon#3]
https://packages.gentoo.org/packages/x11-terms/kitty

**Comment by vitaly-zdanevich** [comment]
Because ico is great!

**Comment by k0nserv** [comment]
Hey, it sounds like you have great advise for Gentoo users. Can you send a PR that adds the instructions to README.md?

**Comment by vitaly-zdanevich** [comment]
I use i3 without panels, start Kitty with a hotkey, so I cannot test new ico - because I do not see any icons :)

I do not know how to replace the ico, maybe somebody else can do it :(

**Comment by k0nserv** [comment]
Ah, it sounded like you had some insight here. Alright, I'll close the  issue then.
