### ISSUE TITLE
SVG version

### ISSUE THREAD

**Issue by SylEleuth** [k0nserv/kitty-icon#4]
Is it possible do add icon in svg format?

**Comment by k0nserv** [comment]
Hey, yeah I should be able to do that. I'm not sure how well SVG will handle the gradients and shadows I've used, but let's see

**Comment by SylEleuth** [comment]
If you don't have it somewhere already I don't see any reasons to making it only for me. I can make it myself from Your png in Inkscape. I'm maintaining icon package and just wanted to add Your version to it, so I'm more interested in shape than colours (which I can add later).

**Comment by k0nserv** [comment]
> If you don't have it somewhere already I don't see any reasons to making it only for me. I can make it myself from Your png in Inkscape. I'm maintaining icon package and just wanted to add Your version to it, so I'm more interested in shape than colours (which I can add later).

I still have the Figma document somewhere so I should be able to dig out an export

**Comment by k0nserv** [comment]
I seem to have lost the original, or at least I cannot find it. Feel free to duplicate it from the png as you suggested.

Sorry I couldn't be of more help

**Comment by SylEleuth** [comment]
No worries. Thank You for Your time.

**Comment by k0nserv** [comment]
Hey, dunno if you ever got around to making an SVG version. I've recreated it in Figma so if not I can share it now

**Comment by SylEleuth** [comment]
I didn't do anything with that so if You can share it I will be grateful.

**Comment by savaobay** [comment]
Does anyone share the svg version?

**Comment by k0nserv** [comment]
Sorry for not getting back on this. I've recreated the icons and tried exporting them as SVG, they don't seem usable though. All of Safari, Firefox, and Chrome fail to render them. I'm attaching one version if anyone wants to debug

 
![Outrun](https://github.com/user-attachments/assets/cc712c9c-1391-4eb5-97a2-98a47a68bbc1)

**Comment by k0nserv** [comment]
Okay, I did some manual editing and it renders, but as predicted the gradients don't quite work

<img width="989" alt="image" src="https://github.com/user-attachments/assets/a6597862-47ff-40ec-8160-94d5e4d7176f">


**Fixed SVG:** [Outrun](https://github.com/user-attachments/assets/6684a6ee-db5d-422e-bed3-e57f47c46c24)
